### ISSUE TITLE
Definir Style Guide de código

### ISSUE THREAD

**Issue by afonsopacifer** [nutriotos/nutriotos#1]
Podemos criar um repo para organizar um style guide para o código, mantendo um padrão para tudo o que escrevermos.

Exemplo: 
https://github.com/LFeh/coding-style

**Comment by iotos** [comment]
Gostei da idéia!
Vamos criar um padrão nosso ou vamos pegar um existente (que você goste) e adaptar?

E gostei de ser em inglês, universaliza tudo.

**Comment by afonsopacifer** [comment]
Podemos pegar um como base, e damos uns toques, varias empresas tem seus styleguides open source, vou listar os mais legais aqui, vou criar um repo para o nosso, e vamos montando la aos poucos, vamos melhorando e deixando com a nossa cara, servindo as nossas necessidades :)

**Comment by iotos** [comment]
http://codeguide.co/

**Comment by iotos** [comment]
Depois de algumas pesquisas feitas, foi escolhido o style guide utilizado pelo Google conforme link acima e podemos ir adequando com as necessidades da empresa.
