### ISSUE TITLE
Style Guide de componentes

### ISSUE THREAD

**Issue by afonsopacifer** [nutriotos/nutriotos#3]
Para escalar, precisamos ir documentando nossos componentes em um styleguide,
isso vai depender do padrão que vamos usar no CSS, mas tem [esse exemplo usando atomic design](http://afonsopacifer.com/demos/microscope/) e a ferramenta que eu fiz o microscope (que nao recomendo pq vamos usar angular, ai acho que da para fazer melhor com outra coisa)

**Comment by iotos** [comment]
Vou criar um style guide seguindo essa referência: [http://style.codeforamerica.org/](http://style.codeforamerica.org/)

**Comment by iotos** [comment]
http://codeguide.co/

**Comment by iotos** [comment]
Atom design feito pelo afonsopacifer - https://github.com/afonsopacifer/microscope

**Comment by iotos** [comment]
Foi escolhido como Style Guide de Componentes o Microscope feito pelo Afonso seguindo o Atom Design.
