### ISSUE TITLE
Página de login do sistema

### ISSUE THREAD

**Issue by iotos** [nutriotos/nutriotos#7]
A página de login e acesso ao sistema deverão seguir as instruções do Backand.com para que os nutricionistas consigam acessar as suas informações.
Pensamos a princípio do login ser o CRN pois é uma numeração única para cada nutricionista e a senha inicial ser o CPF ou alguma coisa que ela já possua e que a qualquer momento possa ser trocada.

**Comment by jarmiotos** [comment]
Ambos os dados já teremos na base, mas como o login deve ser único, ou seja, tanto p o nutricionista qto para o paciente, para mim o login deve ser CPF e a senha inicial a data de aniversário. Porquê ambos tem essa informação e será menos uma consulta ao banco.

**Comment by iotos** [comment]
Então vamos fechar assim:
Login -> CPF
Senha -> Aniversário

@afonsopacifer verifique lá no Backand se o login pode ser feito dessa maneira, caso negativo veja de que maneira tem que ser feito para que a Jéssica mude a regra do negócio.

**Comment by iotos** [comment]
Essa tarefa não será só fazer a tela de login e sim ver toda a funcionalidade de login, por exemplo, as páginas do sistema não podem ser acessadas sem estar logado.

**Comment by afonsopacifer** [comment]
Blz, vou ver um esquema de sessão bem tranquilo para gerenciar isso

**Comment by iotos** [comment]
http://market.ionic.io/starters/firebaseauthstarter
Sistema de login no Firebase 3 com Ionic.
$4.99

##Features

Register Users.
LogIn Users.
Reset Password.
Logout.
Form Validation Ready.
