### ISSUE TITLE
Página de cadastro do Nutricionista

### ISSUE THREAD

**Issue by iotos** [nutriotos/nutriotos#8]
A página da nutricionista tem a peculiaridade de estar em dois ambientes diferentes. O nutricionista irá fazer o cadastro no sistema na página do produto e dentro do sistema também terá o formulário de cadastro mas só para fazer alteração no cadastro dele.

@jarmiotos , não vi todos os campos lá na tabela do Backand, por exemplo, não vi o campo de e-mail. Verifique isso depois.

**Comment by rdfreita** [comment]
Cadastro de Nutricionista conterá os seguintes campos:

- Nome completo
- Sexo
- CPF
- CRN
- Região
- E-mail
- Telefone
- CEP
- Logradouro
- Número
- Complemento
- Bairro
- Cidade
- Estado
- Senha
- Termos de uso e política de privacidade

O único campo que não é obrigatório é o campo "Complemento". 
No CEP implementar o webservice dos Correios que ao digitar o CEP, os campos de logradouro, cidade, estado já se preencherem.
O campo e-mail será o login do usuário.

Nessa demanda ainda não contemplará a parte jurídica do Nutricionista.
Essa demanda visa a criação do Nutricionista no sistema e será implementado no site do produto, ficado a parte da edição e exclusão para dentro do sistema.

**Comment by iotos** [comment]
Cadastro de Nutricionista conterá os seguintes campos:
- Nome completo
- Sexo
- CPF
- CRN
- Região
- E-mail
- Telefone
- CEP
- Logradouro
- Número
- Complemento
- Bairro
- Cidade
- Estado
- Senha
- Termos de uso e política de privacidade

O único campo que não é obrigatório é o campo "Complemento". 
No CEP implementar o webservice dos Correios que ao digitar o CEP, os campos de logradouro, cidade, estado já se preencherem.
O campo e-mail será o login do usuário.

Nessa demanda ainda não contemplará a parte jurídica do Nutricionista.
Essa demanda visa a criação do Nutricionista no sistema e será implementado no site do produto, ficado a parte da edição e exclusão para dentro do sistema.

**Comment by iotos** [comment]
Webservice dos Correios: [https://viacep.com.br/](https://viacep.com.br/)

**Comment by iotos** [comment]
Na validação, verificar se e-mail já existe no banco

**Comment by iotos** [comment]
Demanda feita.
Vou desconsiderar essa última validação pois achei ser rápida de fazer, mas não foi. Deixarei para depois do login implementado pois irá verificar no campo de e-mail para ver se já existe.
